services:
  - type: web
    name: eduelect
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./docs
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 